version: '3'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    command: yarn dev
    depends_on:
      - db
    volumes:
      - .:/usr/app
  db:
    image: mongo:6.0
    container_name: db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: ticket-management-system
